# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [312]:
import numpy as np
ar=np.random.randint(10,24,24)
ar

array([14, 18, 11, 23, 16, 19, 23, 15, 11, 12, 14, 20, 17, 16, 21, 14, 15,
       20, 18, 20, 13, 21, 10, 10])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [120]:
span=50/2
x=np.arange(1,50,span)
len(x)

2

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [121]:
e=np.linspace(4,7,27)
e

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [122]:
a=np.random.rand(5,4)
a=np.around(a,2)
a

array([[0.72, 0.26, 0.55, 0.41],
       [0.18, 0.97, 0.3 , 0.29],
       [0.12, 0.18, 0.49, 0.57],
       [0.22, 0.77, 0.58, 0.17],
       [0.37, 0.47, 0.65, 0.79]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [123]:
b=np.random.randint(5,15,(5,5))
b

array([[12,  6, 11, 13, 10],
       [14, 14, 14,  8,  5],
       [ 5,  7, 13, 13,  7],
       [14, 11, 10, 11, 11],
       [11,  8, 13,  7,  6]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [313]:
np.zeros((20), dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [316]:
np.ones((5,5), dtype=np.float32)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [126]:
ar=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(ar.shape)
print(type(ar))
print(ar.dtype)

(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [317]:
x=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
L=len(x)
row=int(L/2)
col=row
x[row,col]

3

#### 10. Print the all the elements of 3rd row of the matrix

In [127]:
ar[2,:]



array([ 5,  7,  3, 76,  3])

#### 11. Print the all the elements of 4th columns of the matrix

In [128]:
ar[:,3]

array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [129]:
ar[[0,4],:][:,[0,4]]

array([[ 9, 45],
       [23,  8]])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [130]:
m1=np.array([[50,34],[34,65]])
m2=np.array([[7,8],[23,12]])
m3=np.array([[3,76,3],[6,54,6],[8,5,8]])
print('\nm1=\n',m1)
print('\nm2=\n ',m2)
print('\nm3=\n ',m3) 


m1=
 [[50 34]
 [34 65]]

m2=
  [[ 7  8]
 [23 12]]

m3=
  [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [131]:
print(m1.reshape([1,4]))
print(m2.reshape([1,4]))
print(m3.reshape([1,9]))

[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [132]:
print('Vertical',np.concatenate((m1,m2),axis=1))
print('\nHorizontal',np.concatenate((m1,m2),axis=0))

Vertical [[50 34  7  8]
 [34 65 23 12]]

Horizontal [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [153]:
print('Add',m1+m2)
print('\n Sub',m1-m2)
print('\n Mul',m1*m2)
print('\n Div',m1/m2)

Add [[57 42]
 [57 77]]

 Sub [[43 26]
 [11 53]]

 Mul [[350 272]
 [782 780]]

 Div [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [253]:
#ar[[0,4],:][:,[0,4]]
m=m3[[1,2],:][:,[0,1]]
print('m1',m1)
print('\nModified m3',m)
print('\nm1+m3 = \n',m1+m)

m1 [[50 34]
 [34 65]]

Modified m3 [[ 6 54]
 [ 8  5]]

m1+m3 = 
 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [252]:
me=(m1.mean(axis=1))
me1=(me[0])
me2=me[1]
m=me.reshape([1,-1])
m4=np.concatenate((m1,m),axis=0)
print('m4 = \n',m4)

m4 = 
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [251]:
np.matmul(m3,m4)

array([[2860. , 5190.5],
       [2388. , 4011. ],
       [ 906. ,  993. ]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [271]:
ar=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
mean=np.mean(ar,axis=1)
vari=np.var(ar,axis=1)
std=np.std(ar,axis=1)
print('For each Row of Matrix\n')
print('Max and min of Mean',max(mean),'and',min(mean))
print('Max and min of Variance',max(vari),'and',min(vari))
print('Max and min of standard Deviation',max(std),'and',min(std))

For each Row of Matrix

Max and min of Mean 32.6 and 11.2
Max and min of Variance 820.1600000000001 and 39.760000000000005
Max and min of standard Deviation 28.63843571147 and 6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [302]:
run=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]]).reshape([-1,1])
balls=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]]).reshape([-1,1])
avg=run.mean(axis=1) #mean of each player
tot_run=run.sum(axis=1)  #total runs of each player
total_balls=balls.sum(axis=1)   #total no.of balls faced by each player 
strike_rate=tot_run/total_balls
srate=np.sort(strike_rate) [::-1]
averg=np.sort(avg) [::-1]
print('average runs,strike rate')
(averg,srate)

average runs,strike rate


(array([110., 102.,  92.,  78.,  65.,  60.,  56.,  54.,  42.,  32.,  22.,
         12.,  12.,  11.,  10.,   8.,   6.,   3.,   2.,   1.]),
 array([2.07407407, 2.        , 1.42857143, 1.35483871, 1.2       ,
        1.1       , 1.09090909, 1.08      , 1.07368421, 0.91089109,
        0.83333333, 0.74418605, 0.61111111, 0.5       , 0.45454545,
        0.40740741, 0.4       , 0.33333333, 0.25      , 0.14285714]))

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [303]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
Pass=(marks>50).sum()
Fail=(marks<50).sum()
print('No.of.Pass:',Pass,'No.of.Fail:',Fail)

No.of.Pass: 7 No.of.Fail: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [309]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
n1=marks[(marks>45) &(marks <49)]+10
print('mercy mark for score between 45 and 49')
print(n1)
marks1=marks[marks>80]+5
ind2=np.where(marks1>100)
marks1[ind2]=100
print('Bonus marks of students with >80')
print(marks1)
new_mark=np.concatenate((n1,marks1))
print(new_mark)


mercy mark for score between 45 and 49
[57 58]
Bonus marks of students with >80
[ 89  94 100]
[ 57  58  89  94 100]


In [310]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passed=[65,84,56,89,98,77,80]
failed=[47,39,48]
passpercent=(len(passed)/len(marks))*100
passpercent
passed1=[]
failed1=[]
for i in marks:
    if i>44 and i<50:
        passed1.append(i+5)
    elif i>=50 and i<80:
        passed1.append(i)
    elif i>80:
        passed1.append(i+5)
    else:
        failed1.append(i)
updated_pass=[100 if i>100 else i for i in passed1]
passpercent_upd=(len(updated_pass)/len(marks))*100
print("Latest passs percentage",passpercent_upd)
print("Increase in passs percentage",abs(passpercent-passpercent_upd))

Latest passs percentage 80.0
Increase in passs percentage 10.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [311]:
import time
list3=[]
st=time.time()
l1=list(range(1,60001))
l2=list(range(1,60001))
for i,j in zip(l1,l2):
        list3.append((i**2+8)/j)
print((time.time()-st)*1000,'ms')

34.36851501464844 ms


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution



